### ISSUE TITLE
Newtonsoft.Json dependency

### ISSUE THREAD

**Issue by HenrikPoulsen** [daishisystems/Daishi.Microservices#2]
When installing Daishi.Microservices.Components.Serialisation via Nuget it also installs Newtonsoft.Json.
Is it possible to get rid of that? Seems a bit strange that there is a dependency on the package that this one is competing with :)

**Comment by daishisystems** [comment]
Hi, thanks for the comment. Yes, the point of the library is primarily to allow you to dissect large JSON files into manageable segments. The code for this is completely custom, without dependencies. However, I don't want to reinvent the wheel either, and there are some things that JSON.NET does very well in terms of performance; specifically, the JsonTextReader component. JSON# also provides a simple means of deserialisation, which wraps JsonTextReader. Using JsonTextReader alone, you would need to implement quite a lot of custom code, so I've provided the wrapper to make things simpler and provide a more well-rounded solution.

Good point though. I may split the library and include the JSON.NET wrapper as an optional feature.
