### ISSUE TITLE
Portable version

### ISSUE THREAD

**Issue by igorkulman** [daishisystems/Daishi.Microservices#3]
I really like the idea of your JSOn parser (I read the blog posts) and I want to try it in a Windows Phone app. Any chance you could create and publish a portable package?

**Comment by daishisystems** [comment]
Thanks Igor. I'm a bit swamped at the moment, and will publish a portable version ASAP. In the meantime, feel free to fork the project to release a portable package.

**Comment by igorkulman** [comment]
I forked it and converted the Daishi.Microservices.Components.Serialisation into a PCL that could be used with all .NET profiles including Windows Phone. But I have one failing test, I need to reimplement the NameValueCollection because it is only in the full profile.

**Comment by daishisystems** [comment]
Sorry Igor, it will be a few weeks before I can look at this. In the meantime, have you considered [this](http://stackoverflow.com/questions/20268544/portable-class-library-pcl-version-of-httputility-parsequerystring) approach to circumnavigate the PCL NameValueCollection issue?

**Comment by igorkulman** [comment]
I have already solved it, now I have all the tests passing. Nuget now generates a packages targeting portable-net45+win+wpa81+wp80. Just to be sure, I will test it in a console and Windows Phone app and then I may send you a pull request.

**Comment by daishisystems** [comment]
Looking forward to it!
